-- MySQL Script generated by MySQL Workbench
-- Wed Nov  5 01:46:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` BIGINT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `creat_at` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `project_id` BIGINT NULL AUTO_INCREMENT,
  `author_id` BIGINT NULL,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_projects_author_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`documents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`documents` (
  `document_id` BIGINT NULL AUTO_INCREMENT,
  `project_id` BIGINT NULL,
  `title` VARCHAR(255) NULL,
  `content` MEDIUMTEXT NULL,
  `display_order` INT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `fk_documents_project_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_documents_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`versions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`versions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`versions` (
  `version_id` BIGINT NULL AUTO_INCREMENT,
  `document_id` BIGINT NULL,
  `content` MEDIUMTEXT NULL,
  `save_at` TIMESTAMP NULL,
  PRIMARY KEY (`version_id`),
  INDEX `fk_versions_document_idx` (`document_id` ASC) VISIBLE,
  CONSTRAINT `fk_versions_document`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`documents` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collaborators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`collaborators` ;

CREATE TABLE IF NOT EXISTS `mydb`.`collaborators` (
  `project_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `role` ENUM('editor', 'viewer') NULL,
  PRIMARY KEY (`project_id`, `user_id`),
  INDEX `fk_collaborators_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_collaborators_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collaborators_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `comment_id` BIGINT NULL AUTO_INCREMENT,
  `document_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `content` TEXT NULL,
  `is_resolved` TINYINT(1) NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comments_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_document_idx` (`document_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_document`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`documents` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
